GET http://localhost:3000/playerStats

###

GET http://localhost:3000/playerStats/63c8726893a231a5b8c52a55

###

POST http://localhost:3000/playerStats
Content-Type: application/json

{
    "name": "Michael Jordan",
    "number": 90,
    "atBats": 3,
    "battingAverage": 0.25,
    "runs": 4,
    "plateAppearances": 1,
    "runsBattedIn": 1,
    "doubles": 0,           
    "triples": 0,
    "homeruns": 0
}

###

DELETE http://localhost:3000/playerStats/63c86e4183927f2a4a7dffdc

###

PATCH http://localhost:3000/playerStats/63c87d7184bb05dc4cc68d71
Content-Type: application/json

 {
    "runs": 3,
    "battingAverages": "Checking invalid fields generate warnings!",
    "number": 44,
    "gibberish!": "Checking invalid fields generate warnings!"
 }