GET http://localhost:3000/playerStats

###

GET http://localhost:3000/playerStats/63c87d6084bb05dc4cc68d6f

###

POST http://localhost:3000/playerStats
Content-Type: application/json

{
    "name": "Ceelo Green",
    "number": 90,
    "atBats": 3,
    "battingAverage": 0.25,
    "runs": 4,
    "plateAppearances": 1,
    "runsBattedIn": 1,
    "doubles": 0,           
    "triples": 0,
    "homeruns": 0
}

###

DELETE http://localhost:3000/playerStats/63c9005251bb2a59e535e512
###

PATCH http://localhost:3000/playerStats/63c87d7184bb05dc4cc68d71
Content-Type: application/json

 {
    "runs": 3,
    "battingAverages": "Checking invalid fields generate warnings!",
    "number": 46,
    "gibberish!": "Checking invalid fields generate warnings!"
 }