
GET http://localhost:3000/teams

###

GET http://localhost:3000/teams/63c905ecf16cce2949f024c9

###

POST http://localhost:3000/teams
Content-Type: application/json

{
    "mascot": "Wildcats",
    "school": "Checotah High School"
}

###

PATCH http://localhost:3000/teams/63c905ecf16cce2949f024c9
Content-Type: application/json

{
    "mascot": "Big Birds",
    "school": "Checotah High School"
}

###

DELETE http://localhost:3000/teams/63c92301e421260cbe14bd13
